Sube2.HelloMvc/Controllers/OgrenciDersController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Sube2.HelloMvc.Models;

namespace Sube2.HelloMvc.Controllers
{
    public class OgrenciDersController : Controller
    {
        private readonly OkulDbContext _context;

        public OgrenciDersController(OkulDbContext context)
        {
            _context = context;
        }
        public IActionResult Index()
        {                
            return View();
            
        }
        [HttpGet]
        public IActionResult TakenDers(int ogrenciid)
        {
            using(var ctx = new OkulDbContext())
            {
                var lst = ctx.OgrenciDersler
                    .Include(od => od.Ders)
                    .Include(od => od.Ogrenci)
                    .Where(od => od.Ogrenciid == ogrenciid).ToList();
                ViewBag.OgrenciId = ogrenciid;
                return View(lst);
            }
            
        }
        [HttpGet]
        public IActionResult AddOgrDers(int ogrenciid)
        {
            using(var ctx = new OkulDbContext())
            {
                var lst = ctx.OgrenciDersler
                    .Where(od => od.Ogrenciid == ogrenciid)         
                    .Select(od => od.Dersid)
                    .ToList();

                var lst2 = ctx.Dersler.Where(d => !lst.Contains(d.Dersid)).ToList();

                ViewData["OgrenciId"] = ogrenciid;
                return View(lst2);
            }
        }
        [HttpPost]
        public IActionResult AddOgrDers(int ogrenciid,int dersid)
        {
            var ogrenciders = new OgrenciDers
            {
                Ogrenciid = ogrenciid,
                Dersid = dersid
            };
                using (var ctx = new OkulDbContext())
                {
                    ctx.OgrenciDersler.Add(ogrenciders);
                    ctx.SaveChanges();
                }
            
            return RedirectToAction("TakenDers",new { Ogrenciid = ogrenciid });
        }
    }
}

Sube2.HelloMvc/Controllers/StudentController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Sube2.HelloMvc.Models;

namespace Sube2.HelloMvc.Controllers
{
    public class StudentController : Controller
    {
        private readonly OkulDbContext _context;

        public StudentController(OkulDbContext context)
        {
            _context = context;
        }

        public IActionResult Index()
        {
            var lst = _context.Ogrenciler.ToList();
            return View(lst);
        }

        [HttpGet]
        public IActionResult AddStudent()
        {
            return View();
        }

        [HttpPost]
        public IActionResult AddStudent(Ogrenci ogr)
        {
            if (ogr != null)
            {
                using (var ctx = new OkulDbContext())
                {
                    ctx.Ogrenciler.Add(ogr);
                    ctx.SaveChanges();
                }
            }
            return RedirectToAction("Index");
        }

        public IActionResult EditStudent(int id)
        {
            using (var ctx = new OkulDbContext())
            {
                var ogr = ctx.Ogrenciler.Find(id);
                return View(ogr);
            }
        }

        [HttpPost]
        public IActionResult EditStudent(Ogrenci ogr)
        {
            if (ogr != null)
            {
                using (var ctx = new OkulDbContext())
                {
                    ctx.Entry(ogr).State = EntityState.Modified;
                    ctx.SaveChanges();
                }
            }
            return RedirectToAction("Index");
        }

        public IActionResult DeleteStudent(int id)
        {
            using (var ctx = new OkulDbContext())
            {
                ctx.Ogrenciler.Remove(ctx.Ogrenciler.Find(id));
                ctx.SaveChanges();
            }
            return RedirectToAction("Index");
        }
    }
}

Sube2.HelloMvc/Views/Student/Index.cshtml
@model IEnumerable<Ogrenci>
@{
    ViewData["Title"] = "Öğrenciler";
}

<h1>Öğrenci İşlemleri</h1>
<div>
    <a asp-action="AddStudent" asp-controller="Student" class="btn btn-outline-primary">Öğrenci Ekle</a>
</div>
<div>
    <table class="table table-bordered">
        <thead>
            <tr>
                <th>Numara</th>
                <th>Ad</th>
                <th>Soyad</th>
                <th>İşlemler</th>
                <th>Dersler</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
                <tr>
                    <td>@item.Numara</td>
                    <td>@item.Ad</td>
                    <td>@item.Soyad</td>
                    <td><a class="btn btn-sm btn-outline-success" href="/Student/EditStudent/@item.Ogrenciid">Düzenle</a> | <a onclick="return confirm('Emin misiniz?')" class="btn btn-sm btn-outline-danger" href="/Student/DeleteStudent/@item.Ogrenciid">Sil</a></td>
                    <td><a class="btn btn-outline-primary" asp-action="TakenDers" asp-controller="OgrenciDers" asp-route-ogrenciId="@item.Ogrenciid">Derslere Git</a></td>
                </tr>
            }
        </tbody>
    </table>
</div>