Sube2.HelloMvc/Controllers/DersController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Sube2.HelloMvc.Models;

namespace Sube2.HelloMvc.Controllers
{
    public class DersController : Controller
    {
        private readonly OkulDbContext _context;

        public DersController(OkulDbContext context)
        {
            _context = context;
        }
        public IActionResult Index()
        {
            using (var ctx = new OkulDbContext())
            {

                var lst = ctx.Dersler.ToList();
                return View(lst);
            }
        }
        [HttpGet]
        public IActionResult AddDers()
        {
            return View();
        }
        [HttpPost]
        public IActionResult AddDers(Ders ders) 
        {
            if (ders !=null)
            {
                using (var ctx = new OkulDbContext())
                {
                    ctx.Dersler.Add(ders);
                    ctx.SaveChanges();
                }
                

                //// Öğrenciye ders ekleme işlemi
                //using(var ctx = new OkulDbContext())
                //{
                //    var ogrenciDers = new OgrenciDers { Ogrenciid = ogrenciId, Dersid = ders.Dersid };
                //    ctx.OgrenciDersler.Add(ogrenciDers);
                //    ctx.SaveChanges();
                //}
                
                //_context.OgrenciDersler.Add(ogrenciDers);
                //_context.SaveChanges();

                return RedirectToAction("Index");
            }
            return View(ders);
        }

        [HttpGet]
        public IActionResult EditDers(int dersid)
        {
            using(var ctx = new OkulDbContext()) 
            {
                var ders = ctx.Dersler.Find(dersid);
                if(ders==null)
                {
                    return NotFound();
                }
                return View(ders);
            }
        }
        [HttpPost]
        public IActionResult EditDers(Ders ders)
        {
            if (ders != null)
            {
                using (var ctx = new OkulDbContext())
                {
                    ctx.Entry(ders).State = EntityState.Modified;
                    ctx.SaveChanges();
                }
            }
            return RedirectToAction("Index");
        }

        public IActionResult DeleteDers(int dersid)
        {
            using (var ctx = new OkulDbContext())
            {
                ctx.Dersler.Remove(ctx.Dersler.Find(dersid));
                ctx.SaveChanges();
            }
            return RedirectToAction("Index");
        }
    }
}

Sube2.HelloMvc/Controllers/StudentController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Sube2.HelloMvc.Models;

namespace Sube2.HelloMvc.Controllers
{
    public class StudentController : Controller
    {
        private readonly OkulDbContext _context;

        public StudentController(OkulDbContext context)
        {
            _context = context;
        }

        public IActionResult Index()
        {
            var lst = _context.Ogrenciler.ToList();
            return View(lst);
        }

        [HttpGet]
        public IActionResult AddStudent()
        {
            return View();
        }

        [HttpPost]
        public IActionResult AddStudent(Ogrenci ogr)
        {
            if (ogr != null)
            {
                using (var ctx = new OkulDbContext())
                {
                    ctx.Ogrenciler.Add(ogr);
                    ctx.SaveChanges();
                }
            }
            return RedirectToAction("Index");
        }

        public IActionResult EditStudent(int id)
        {
            using (var ctx = new OkulDbContext())
            {
                var ogr = ctx.Ogrenciler.Find(id);
                return View(ogr);
            }
        }

        [HttpPost]
        public IActionResult EditStudent(Ogrenci ogr)
        {
            if (ogr != null)
            {
                using (var ctx = new OkulDbContext())
                {
                    ctx.Entry(ogr).State = EntityState.Modified;
                    ctx.SaveChanges();
                }
            }
            return RedirectToAction("Index");
        }

        public IActionResult DeleteStudent(int id)
        {
            using (var ctx = new OkulDbContext())
            {
                ctx.Ogrenciler.Remove(ctx.Ogrenciler.Find(id));
                ctx.SaveChanges();
            }
            return RedirectToAction("Index");
        }
    }
}

Sube2.HelloMvc/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - İnt Prog</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Sube2.HelloMvc.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-lg navbar-dark gradient-custom navbar-toggleable-sm" >
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">İnternet Programcılığı</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav me-auto d-flex flex-row mt-3 mt-lg-0">
                        <li class="nav-item text-center mx-2 mx-lg-1">
                            <a class="nav-link text-light" asp-area="" asp-controller="Home" asp-action="Index">Anasayfa</a>
                        </li>
                        <li class="nav-item text-center mx-2 mx-lg-1">
                            <a class="nav-link text-light" asp-area="" asp-controller="Student" asp-action="Index">Öğrenci İşlemleri</a>
                        </li>
                        <li class="nav-item text-center mx-2 mx-lg-1">
                            <a class="nav-link text-light" asp-area="" asp-controller="Ders" asp-action="Index">Ders İşlemleri</a>
                        </li>
                        <li class="nav-item text-center mx-2 mx-lg-1">
                            <a class="nav-link text-light" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - Sube2.HelloMvc - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>